---
notifications:
  email:
  - team@appwrite.io

language: minimal

arch:
  - amd64
  - arm64

os: linux

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

install:
  - docker-compose up -d

script:
  - sleep 10
  - docker ps -a
  - docker-compose logs telegraf
  - >
    if : >/dev/tcp/localhost/8094; then
      echo 'Connection available.'
      travis_terminate 0
    else
      echo 'Connection unavailable.'
      travis_terminate 1
    fi


deploy:
  - provider: script
    edge: true
    script: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x -t appwrite/telegraf:$TRAVIS_TAG ./ --push
    on:
      tags: true