---
version: '3'

services:
  telegraf:
    build: .
    restart: unless-stopped
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8094:8094/tcp"
    environment: 
      - _APP_INFLUXDB_HOST=influxdb
      - _APP_INFLUXDB_PORT=8086
